### PR TITLE
finish week_0_part_1

### PR DESCRIPTION
**Pull request by ArthurLinDev**
Let's add this deleted line back.

### CODE REVIEW

**Comment by DingChiLin** [comment]
Let's add this deleted line back.

**Comment by DingChiLin** [comment]
HI New comment

**Comment by ArthurLinDev** [comment]
fixed

**Comment by DingChiLin** [comment]
which one is comment?

**Comment by DingChiLin** [comment]
HELLO WORLD?

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
**### hello** ad f

**Comment by DingChiLin** [comment]
{error: compare branch name is wrong, should be **week_n_part_m**. Please **Close** this pull request and create a new one.}

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
{error: base branch should be **arthur_develop**. Please **Close** this pull request and create a new one.}

**Comment by DingChiLin** [comment]
????

**Comment by DingChiLin** [comment]
!!!

**Comment by DingChiLin** [comment]
A

**Comment by DingChiLin** [comment]
ZZZ

**Comment by DingChiLin** [comment]
EEEE

**Comment by DingChiLin** [comment]
RRR

**Comment by DingChiLin** [comment]
{error: comment on a wrong pull request, note: please contact Arthur for this problem}

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
HI

**Comment by DingChiLin** [comment]
YYY

**Comment by DingChiLin** [comment]
Fixed

**Comment by DingChiLin** [comment]
{error: comment on a wrong pull request, note: please contact Arthur for this problem}

**Comment by DingChiLin** [comment]
fixed

**Comment by DingChiLin** [comment]
{error: comment on a wrong pull request, note: please contact Arthur for this problem}

**Comment by DingChiLin** [comment]
fixed

**Comment by DingChiLin** [comment]
{error: comment on a wrong pull request, note: please contact Arthur for this problem}

**Comment by DingChiLin** [comment]
Fixed

**Comment by DingChiLin** [comment]
{error: comment on a wrong pull request, note: please contact Arthur for this problem}

**Comment by DingChiLin** [comment]
Cannot read property 'name' of undefined

**Comment by DingChiLin** [comment]
{error: comment on a wrong pull request, note: please contact Arthur for this problem}

**Comment by DingChiLin** [comment]
{error: comment on a wrong pull request, note: please contact Arthur for this problem}

**Comment by DingChiLin** [comment]
{error: comment on a wrong pull request, note: please contact Arthur for this problem}

**Comment by DingChiLin** [comment]
{error: comment on a wrong pull request, note: please contact Arthur for this problem}

**Comment by DingChiLin** [comment]
{error: comment on a wrong pull request, note: please contact Arthur for this problem}

**Comment by DingChiLin** [comment]
{error: comment on a wrong pull request, note: please contact Arthur for this problem}

**Comment by DingChiLin** [comment]
???

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Yo

**Comment by DingChiLin** [comment]
。。

**Comment by DingChiLin** [comment]
111

**Comment by DingChiLin** [comment]
彭彭

**Comment by DingChiLin** [comment]
fixed

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just pass the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just passed the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just passed the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just passed the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just passed the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just passed the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
Congrats! You just passed the basic validation. Arthur is on the way.

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Cannot read property 'name' of undefined"

**Comment by DingChiLin** [comment]
"Cannot read property 'name' of undefined"

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Cannot read property 'name' of undefined"

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"{uri: http://13.230.176.178/api/1.0/products/all, error: 502 - \"<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body>\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.20.1</center>\\r\\n</body>\\r\\n</html>\\r\\n\"}"

**Comment by DingChiLin** [comment]
"{uri: http://13.230.176.178/api/1.0/products/all, error: 502 - \"<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body>\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.20.1</center>\\r\\n</body>\\r\\n</html>\\r\\n\"}"

**Comment by DingChiLin** [comment]
"{uri: http://13.230.176.178/api/1.0/products/all, error: 502 - \"<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body>\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.20.1</center>\\r\\n</body>\\r\\n</html>\\r\\n\"}"

**Comment by DingChiLin** [comment]
"{uri: http://13.230.176.178/api/1.0/products/all, error: 502 - \"<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body>\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.20.1</center>\\r\\n</body>\\r\\n</html>\\r\\n\"}"

**Comment by DingChiLin** [comment]
"{uri: http://13.230.176.178/api/1.0/products/all, error: 502 - \"<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body>\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.20.1</center>\\r\\n</body>\\r\\n</html>\\r\\n\"}"

**Comment by DingChiLin** [comment]
"{uri: http://13.230.176.178/api/1.0/products/all, error: 502 - \"<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body>\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.20.1</center>\\r\\n</body>\\r\\n</html>\\r\\n\"}"

**Comment by DingChiLin** [comment]
"{uri: http://13.230.176.178/api/1.0/products/all, error: 502 - \"<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body>\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.20.1</center>\\r\\n</body>\\r\\n</html>\\r\\n\"}"

**Comment by DingChiLin** [comment]
"{uri: http://13.230.176.178/api/1.0/products/all, error: 502 - \"<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body>\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.20.1</center>\\r\\n</body>\\r\\n</html>\\r\\n\"}"

**Comment by DingChiLin** [comment]
"{uri: http://13.230.176.178/api/1.0/products/all, error: 502 - \"<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body>\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.20.1</center>\\r\\n</body>\\r\\n</html>\\r\\n\"}"

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Comment by DingChiLin** [comment]
"Congrats! You just passed the basic validation. Arthur is on the way."

**Pull request merged**
